### ISSUE TITLE
Conditions not ok using {cart.price+tax+discount} with a coupon code.

### ISSUE THREAD

**Issue by stepp24** [owebia/magento1-module-advanced-shipping#9]
Hello,

I am using Magento 1.9.3.6 and Owebia v2.6. I think I have found something wrong with conditions and {cart.price+tax+discount}. I tried to setup 2 shipping rules like this :

`"conditions": "{cart.price+tax+discount} < 250.0", "fees": 9.5`

`"conditions": "{cart.price+tax+discount} >= 250.0", "fees": 0,`

So, I should get free shipping when cart total (discount incl.) is above 250,00. All is ok without discount coupon, but it is not ok when using a discount coupon.

When debugging, I found in constructor of class Owebia_Shipping2_Model_Os2_Data_Cart that calculation of $totalInclTaxWithDiscount was wrong because :
- It takes base_row_total which is the row cart amount (tax excl. and discount excl.)
- minus base_discount_amount (calculated on row cart amount tax excl. and discount incl. => /!\ with discount incl. calculated on row cart amount tax incl.)
- plus tax_amount (calculated on row cart amount tax excl. and discount incl.) :
`$totalInclTaxWithDiscount += $item->getData('base_row_total') - $item->getData('base_discount_amount' + $item->getData('tax_amount');`

This way, the base_discount_amount is wrong and higher than it should, and value of {cart.price+tax+discount} is smaller than it should.

So with a total cart of 251,00 (discount incl.), I don't get free shipping because calculated {cart.price+tax+discount} is < 250,00.

- In fact, I think base_discount_amount should be calculated on row cart amount tax excl. So, a potential fix could be something like this :
`$totalInclTaxWithDiscount += $item->getData('base_row_total') - ($item->getData('base_discount_amount') / (1+($item->getData('tax_percent')/100)))
                + $item->getData('tax_amount');`

With this fix, conditions are applied properly.

There is maybe the same problem with $totalExclTaxWithDiscount.

What do you think about it ?

Regards.

**Comment by owebia** [comment]
Hi,

I think that you have found a configuration related issue but I fear that your fix will no be adapted to other vat configurations.

I need to do more investigations.
Can you send me your tax configuration please?

Regards,
A.L.

**Comment by stepp24** [comment]
Hi, thanks for your reply, here are my tax calculation settings : 
- Tax Calculation Method Based On : Unit Price
- Tax Calculation Based On : Shipping Address
- Catalog Prices : Including tax
- Shipping Prices : Including tax
- Apply Customer Tax : After discount
- Apply Discount On Prices : Including tax
- Apply Tax On : Custom price if available
- Enable Cross Border Trade : no

Regards.

**Comment by owebia** [comment]
Hi @stepp24  
I have made some tests and found a fix.  

It seems that discount includes tax only when Catalog Prices = Including Tax.

Does it seem correct for you?

## Default Tax Calculation Settings (US and CA recommendation)

- Tax Calculation Method Based On: `Total`
- Tax Calculation Based On: `Shipping Address`
- Catalog Prices: `Excluding Tax`
- Shipping Prices: `Excluding Tax`
- Apply Customer Tax: **`After Discount`** (default)
- Apply Discount On Prices: **`Excluding Tax`** (default)
- Apply Tax On: `Custom price if available`
- Enable Cross Border Trade: `No`

![shopping cart 2](https://user-images.githubusercontent.com/604741/32522807-148fc656-c419-11e7-8306-83482574d28d.png)

- Subtotal        100.00 €
- Discount (10%)  -10.00 € (excl. tax)
- Tax (20%)        18.00 € `( (100 - 10) * 0.2 = 18 )`
- Grand Total     108.00 € `( 100 - 10 + 18 = 108 )`

### Before and after fix

- `{cart.price-tax-discount} = 100`
- `{cart.price-tax+discount} = 90  ( 100 - 100 * 0.1 = 90 )`
- `{cart.price+tax-discount} = 120 ( 100 * 1.2 = 120 )`
- `{cart.price+tax+discount} = 108 ( 90 * 1.2 = 108 )`

## Recommended EU Tax Calculation Settings

See http://docs.magento.com/m1/ce/user_guide/tax/warning-messages.html

- Tax Calculation Method Based On: `Total`
- Tax Calculation Based On: `Shipping Address`
- Catalog Prices: `Excluding Tax`
- Shipping Prices: `Excluding Tax`
- Apply Customer Tax: **`After Discount`** (default)
- Apply Discount On Prices: **`Including Tax`**
- Apply Tax On: `Custom price if available`
- Enable Cross Border Trade: `No`

![shopping cart 3](https://user-images.githubusercontent.com/604741/32522843-2e951c54-c419-11e7-961f-77790fad330c.png)

- Subtotal        100.00 €
- Discount (10%)  -12.00 € (calculated on prices incl. tax but the value is excl. tax)
- Tax (20%)        17.60 € ( (100 - 12) * 0.2 = 17.6 )
- Grand Total     105.60 € ( 100 - 12 + 17.6 = 105.6 )

### Before and after fix

- `{cart.price-tax-discount} = 100`
- `{cart.price-tax+discount} = 88    ( 100 - 100 * 0.1 * 1.2 = 88 )`
- `{cart.price+tax-discount} = 120   ( 100 * 1.2 = 120 )`
- `{cart.price+tax+discount} = 105.6 ( 88 * 1.2 = 105.6 )`

## Test 1 ( @stepp24 's configuration )

- Tax Calculation Method Based On: **`Unit Price`**
- Tax Calculation Based On: `Shipping Address`
- Catalog Prices: **`Including Tax`**
- Shipping Prices: **`Including Tax`**
- Apply Customer Tax: `After Discount`
- Apply Discount On Prices: **`Including Tax`**
- Apply Tax On: `Custom price if available`
- Enable Cross Border Trade: `No`

![shopping cart 4](https://user-images.githubusercontent.com/604741/32522876-4dfbf1d0-c419-11e7-9c13-16e5afc4e0f4.png)

- Subtotal         83.30 €
- Discount (10%)  -10.00 € (incl. tax because Catalog Prices = Including Tax)
- Tax (20%)        15.00 € ( (83.3 - 10 / 1.2) * 0.2 = 75 )
- Grand Total      90.00 € ( 83.3 - 10 / 1.2 + 15 = 90 )

### Before fix

- `{cart.price-tax-discount} = 83.3`
- `{cart.price-tax+discount} = 73.33 ( 83.3 - 83.3 * 0.1 * 1.2 = 73.30 )`
- `{cart.price+tax-discount} = 100`
- `{cart.price+tax+discount} = 88.33 ( 100 - 100 * 0.1 * 1.2 = 88 )`

### After fix

- `{cart.price-tax-discount} = 83.3`
- `{cart.price-tax+discount} = 74.966666666667 ( 83.3 - 83.3 * 0.1 = 75 )`
- `{cart.price+tax-discount} = 100 (83.3 * 1.2 = 100)`
- `{cart.price+tax+discount} = 90  (75 * 1.2 = 90)`

## Test 2

- Tax Calculation Method Based On: **`Unit Price`**
- Tax Calculation Based On: `Shipping Address`
- Catalog Prices: **`Including Tax`**
- Shipping Prices: **`Including Tax`**
- Apply Customer Tax: `After Discount`
- Apply Discount On Prices: **`Excluding Tax`** (default)
- Apply Tax On: `Custom price if available`
- Enable Cross Border Trade: `No`

![shopping cart 5](https://user-images.githubusercontent.com/604741/32522921-7a759f40-c419-11e7-8c62-83e55e19d378.png)

- Subtotal         83.33 €
- Discount (10%)   -8.33 € (incl. tax because Catalog Prices = Including Tax)
- Tax (20%)        15.28 € ( (83.33 - 8.33 / 1.2) * 0.2 = 15.28 )
- Grand Total      91.67 € ( 83.33 - 8.33 / 1.2 + 15.28 = 91.67 )

### Before fix

- `{cart.price-tax-discount} = 83.33`
- `{cart.price-tax+discount} = 75 ( 83.33 - 83.33 * 0.1 = 75 )`
- `{cart.price+tax-discount} = 100`
- `{cart.price+tax+discount} = 90.28 ( 100 - 100 * 0.1 = 90 )`

### After fix

- `{cart.price-tax-discount} = 83.33`
- `{cart.price-tax+discount} = 76.388333333333 ( 83.33 - 83.33 * 0.1 / 1.2 = 76.39 )`
- `{cart.price+tax-discount} = 100 ( 83.33 * 1.2 = 100 )`
- `{cart.price+tax+discount} = 91.67 ( 76.39 * 1.2 = 91.67 )`

**Comment by stepp24** [comment]
Hello @owebia,

Sorry for the late reply.

After having taken time to look at your examples, results of your fix seems all good to me.

I'll test the fix when it will be available.

Thank you very much for the time you spent on this.

**Comment by owebia** [comment]
Hi @stepp24, you can download the new release of the module: 2.6.3

Best Regards,
